# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Work\nemo-audio-profanity-detector-app\src\main\ui\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labForFilePath = QtWidgets.QLabel(self.centralwidget)
        self.labForFilePath.setObjectName("labForFilePath")
        self.horizontalLayout.addWidget(self.labForFilePath)
        self.edtFilePath = QtWidgets.QLineEdit(self.centralwidget)
        self.edtFilePath.setReadOnly(True)
        self.edtFilePath.setObjectName("edtFilePath")
        self.horizontalLayout.addWidget(self.edtFilePath)
        self.btnOpen = QtWidgets.QPushButton(self.centralwidget)
        self.btnOpen.setObjectName("btnOpen")
        self.horizontalLayout.addWidget(self.btnOpen)
        self.btnLoadModel = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoadModel.setObjectName("btnLoadModel")
        self.horizontalLayout.addWidget(self.btnLoadModel)
        self.btnStart = QtWidgets.QPushButton(self.centralwidget)
        self.btnStart.setObjectName("btnStart")
        self.horizontalLayout.addWidget(self.btnStart)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labForBadWords = QtWidgets.QLabel(self.centralwidget)
        self.labForBadWords.setObjectName("labForBadWords")
        self.verticalLayout_2.addWidget(self.labForBadWords)
        self.txtBadWords = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.txtBadWords.setObjectName("txtBadWords")
        self.verticalLayout_2.addWidget(self.txtBadWords)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.labForResult = QtWidgets.QLabel(self.centralwidget)
        self.labForResult.setObjectName("labForResult")
        self.verticalLayout_6.addWidget(self.labForResult)
        self.listResult = QtWidgets.QListWidget(self.centralwidget)
        self.listResult.setObjectName("listResult")
        self.verticalLayout_6.addWidget(self.listResult)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Audio Badwords Detector"))
        self.labForFilePath.setText(_translate("MainWindow", "Audio File: "))
        self.btnOpen.setText(_translate("MainWindow", "Open"))
        self.btnLoadModel.setText(_translate("MainWindow", "Load Model"))
        self.btnStart.setText(_translate("MainWindow", "Start"))
        self.labForBadWords.setText(_translate("MainWindow", "Bad Words"))
        self.txtBadWords.setPlaceholderText(_translate("MainWindow", "Type bad words separated by \",\""))
        self.labForResult.setText(_translate("MainWindow", "Result"))
